name: aws
author: syh8088
description: 'Use aws in github action'
inputs:
  AWS_REGION:
    description: 'Set AWS REGION'
    required: true
    default: 'ap-northeast-2'
  AWS_ROLE_TO_ASSUME:
    description: 'Set AWS Assume Role arn'
    required: true
    default: 'arn:aws:iam::123456789:role/GithubActions'

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials
    id: credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-region: ${{ inputs.AWS_REGION }}
      role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
